import {
  Activity,
  Archive,
  Blocks,
  Bot,
  Boxes,
  ChevronDown,
  CircleCheck,
  FlaskConical,
  FolderKanban,
  Home,
  KeyRound,
  PanelLeftClose,
  Play,
  Search,
  Settings2,
  ShieldCheck,
  Sparkles,
  UsersRound,
} from 'lucide-react';

export const icons = {
  home: Home,
  projects: FolderKanban,
  missions: Activity,
  team: UsersRound,
  skills: Blocks,
  evidence: ShieldCheck,
  settings: Settings2,
  labs: FlaskConical,
  bot: Bot,
  archive: Archive,
  boxes: Boxes,
  key: KeyRound,
  play: Play,
  search: Search,
  collapse: PanelLeftClose,
  sparkles: Sparkles,
  check: CircleCheck,
  down: ChevronDown,
} as const;
